apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ores
  annotations:
    github.com/project-slug: equinor/ores
spec:
  type: other
  lifecycle: unknown
  owner: interpretations-rddms