#!/usr/bin/env python3
"""
ingest_wells.py — Ingest WeCo demo wells into RDDMS
=====================================================

Reads RESQML JSON payloads (generated by generate_payloads.py) and ingests
them into one or more RDDMS instances via the Reservoir-DDMS REST API.

Target instances:
  - eqndev (default)  — development environment
  - preship           — pre-ship testing
  - interop           — interoperability testing

The script creates the ``maap/weco`` dataspace if it does not exist, then
ingests all well trajectories, logs, and markers.

Usage::

    # Ingest to default (eqndev):
    python demo/resqml/ingest_wells.py --token-file ~/.azure/token.json

    # Ingest to specific instance:
    python demo/resqml/ingest_wells.py --instance preship --token-file ~/.azure/token.json

    # Ingest to all three instances:
    python demo/resqml/ingest_wells.py --all --token-file ~/.azure/token.json

    # Dry-run (validate payloads without sending):
    python demo/resqml/ingest_wells.py --dry-run

Prerequisites:
  - Generate payloads first: python demo/resqml/generate_payloads.py
  - Azure AD token (file, env var, or az cli)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


# ═══════════════════════════════════════════════════════════════════════════
#  RDDMS Instance Configuration
# ═══════════════════════════════════════════════════════════════════════════

INSTANCES = {
    "eqndev": {
        "url": os.environ.get(
            "RDDMS_URL_EQNDEV",
            "https://reservoir-ddms.eqndev.radix.equinor.com/api/v2",
        ),
        "description": "Development (eqndev)",
    },
    "preship": {
        "url": os.environ.get(
            "RDDMS_URL_PRESHIP",
            "https://reservoir-ddms.preship.radix.equinor.com/api/v2",
        ),
        "description": "Pre-ship testing",
    },
    "interop": {
        "url": os.environ.get(
            "RDDMS_URL_INTEROP",
            "https://reservoir-ddms.interop.radix.equinor.com/api/v2",
        ),
        "description": "Interoperability testing",
    },
}

TARGET_DATASPACE = "maap/weco"
PAYLOADS_DIR = Path(__file__).parent / "payloads"


# ═══════════════════════════════════════════════════════════════════════════
#  Authentication (same as demo_rddms.py)
# ═══════════════════════════════════════════════════════════════════════════

def acquire_token(token_file: str = None) -> str:
    """Acquire Azure AD token from multiple sources."""
    # 1. Direct file
    if token_file and os.path.isfile(token_file):
        with open(token_file) as f:
            data = json.load(f)
        token = data.get("access_token") or data.get("token")
        if token:
            print(f"  [auth] Token from file: {token_file}")
            return token

    # 2. ORES cache
    ores_token = os.path.expanduser("~/.ores/token.json")
    if os.path.isfile(ores_token):
        with open(ores_token) as f:
            data = json.load(f)
        token = data.get("access_token") or data.get("token")
        if token:
            print("  [auth] Token from ORES cache")
            return token

    # 3. Azure CLI
    try:
        import subprocess
        result = subprocess.run(
            ["az", "account", "get-access-token",
             "--resource", "https://storage.azure.com"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            token = data.get("accessToken")
            if token:
                print("  [auth] Token from Azure CLI")
                return token
    except Exception:
        pass

    # 4. Environment variable
    token = os.environ.get("RDDMS_TOKEN") or os.environ.get("OSDU_TOKEN")
    if token:
        print("  [auth] Token from environment variable")
        return token

    raise RuntimeError(
        "Cannot acquire authentication token.\n"
        "Provide --token-file, set RDDMS_TOKEN/OSDU_TOKEN env var, "
        "or login with 'az login'."
    )


# ═══════════════════════════════════════════════════════════════════════════
#  RDDMS Client
# ═══════════════════════════════════════════════════════════════════════════

class RddmsClient:
    """Simple synchronous RDDMS client for ingestion."""

    def __init__(self, base_url: str, token: str, dataspace: str):
        import httpx
        self.base_url = base_url.rstrip("/")
        self.dataspace = dataspace
        self.client = httpx.Client(
            base_url=self.base_url,
            headers={
                "Authorization": f"Bearer {token}",
                "data-partition-id": dataspace,
                "Content-Type": "application/json",
            },
            timeout=60.0,
        )

    def ensure_dataspace(self) -> bool:
        """Create target dataspace if it doesn't exist."""
        try:
            resp = self.client.get(f"/dataspaces/{self.dataspace}")
            if resp.status_code == 200:
                print(f"  Dataspace '{self.dataspace}' exists")
                return True
        except Exception:
            pass

        # Try to create it
        try:
            resp = self.client.put(
                f"/dataspaces/{self.dataspace}",
                json={"description": "WeCo demo well data"},
            )
            if resp.status_code in (200, 201):
                print(f"  Created dataspace '{self.dataspace}'")
                return True
            else:
                print(f"  WARN: Could not create dataspace: {resp.status_code} {resp.text}")
                return False
        except Exception as e:
            print(f"  WARN: Dataspace creation failed: {e}")
            return False

    def ingest_objects(self, objects: list, object_type: str) -> int:
        """Ingest a batch of RESQML objects into RDDMS."""
        if not objects:
            return 0

        # RDDMS batch ingest endpoint
        batch_size = 50
        total = 0

        for i in range(0, len(objects), batch_size):
            batch = objects[i:i + batch_size]
            try:
                resp = self.client.put(
                    "/objects",
                    json=batch,
                )
                if resp.status_code in (200, 201):
                    total += len(batch)
                else:
                    print(f"    WARN: Batch {i//batch_size + 1} failed: "
                          f"{resp.status_code} — {resp.text[:200]}")
            except Exception as e:
                print(f"    ERROR: Batch {i//batch_size + 1}: {e}")

        return total

    def close(self):
        self.client.close()


# ═══════════════════════════════════════════════════════════════════════════
#  Ingestion Logic
# ═══════════════════════════════════════════════════════════════════════════

def load_payloads(dataset_dir: Path) -> dict:
    """Load all JSON payload files from a dataset directory."""
    payloads = {}
    for json_file in sorted(dataset_dir.glob("*.json")):
        if json_file.name == "manifest.json":
            continue
        with open(json_file) as f:
            data = json.load(f)
        payloads[json_file.stem] = data
    return payloads


def ingest_dataset(client: RddmsClient, dataset_name: str,
                   dry_run: bool = False) -> dict:
    """Ingest one dataset into RDDMS."""
    dataset_dir = PAYLOADS_DIR / dataset_name
    if not dataset_dir.exists():
        print(f"    SKIP: No payloads found at {dataset_dir}")
        print(f"    Run: python demo/resqml/generate_payloads.py --dataset {dataset_name}")
        return {}

    payloads = load_payloads(dataset_dir)
    if not payloads:
        print(f"    SKIP: No JSON files in {dataset_dir}")
        return {}

    summary = {"dataset": dataset_name}

    for obj_type, objects in payloads.items():
        n = len(objects)
        if dry_run:
            print(f"    [dry-run] Would ingest {n} {obj_type} objects")
            summary[obj_type] = n
        else:
            t0 = time.time()
            ingested = client.ingest_objects(objects, obj_type)
            elapsed = time.time() - t0
            print(f"    Ingested {ingested}/{n} {obj_type} objects "
                  f"({elapsed:.1f}s)")
            summary[obj_type] = ingested

    return summary


def ingest_instance(instance_name: str, token: str,
                    datasets: list, dry_run: bool = False) -> dict:
    """Ingest all datasets into one RDDMS instance."""
    inst = INSTANCES[instance_name]
    print(f"\n{'─' * 50}")
    print(f"  Instance: {inst['description']} ({instance_name})")
    print(f"  URL: {inst['url']}")
    print(f"  Dataspace: {TARGET_DATASPACE}")
    print(f"{'─' * 50}")

    if dry_run:
        print("  [dry-run mode — no actual HTTP calls]")
        results = {}
        for ds in datasets:
            print(f"\n  [{ds}]")
            results[ds] = ingest_dataset(None, ds, dry_run=True)
        return results

    client = RddmsClient(inst["url"], token, TARGET_DATASPACE)
    try:
        client.ensure_dataspace()

        results = {}
        for ds in datasets:
            print(f"\n  [{ds}]")
            results[ds] = ingest_dataset(client, ds)
        return results
    finally:
        client.close()


# ═══════════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Ingest WeCo demo wells into RDDMS",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--instance", choices=list(INSTANCES.keys()), default="eqndev",
        help="Target RDDMS instance (default: eqndev)",
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Ingest to all three instances",
    )
    parser.add_argument(
        "--dataset",
        help="Ingest only one dataset (default: all available)",
    )
    parser.add_argument(
        "--token-file",
        help="Path to JSON token file",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate payloads without sending to RDDMS",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("  WeCo Demo Well Ingestion → RDDMS")
    print("=" * 60)

    # Check payloads exist
    if not PAYLOADS_DIR.exists():
        print(f"\nERROR: Payloads not found at {PAYLOADS_DIR}")
        print("Run first: python demo/resqml/generate_payloads.py")
        sys.exit(1)

    # Determine datasets
    available = [d for d in PAYLOADS_DIR.iterdir()
                 if d.is_dir() and (d / "wells.json").exists()]
    if not available:
        print(f"\nERROR: No dataset payloads found in {PAYLOADS_DIR}")
        print("Run first: python demo/resqml/generate_payloads.py")
        sys.exit(1)

    if args.dataset:
        datasets = [args.dataset]
    else:
        datasets = [d.name for d in available]

    print(f"\n  Datasets: {datasets}")
    print(f"  Target dataspace: {TARGET_DATASPACE}")

    # Authenticate (skip for dry-run)
    token = None
    if not args.dry_run:
        token = acquire_token(args.token_file)

    # Determine instances
    instances = list(INSTANCES.keys()) if args.all else [args.instance]

    # Ingest
    all_results = {}
    for inst_name in instances:
        all_results[inst_name] = ingest_instance(
            inst_name, token, datasets, dry_run=args.dry_run,
        )

    # Summary
    print(f"\n{'=' * 60}")
    print("  Summary")
    print(f"{'=' * 60}")
    for inst_name, results in all_results.items():
        print(f"\n  {inst_name}:")
        for ds_name, ds_result in results.items():
            total = sum(v for k, v in ds_result.items() if k != "dataset")
            print(f"    {ds_name}: {total} objects")


if __name__ == "__main__":
    main()
