#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_businessdecision_drogon.py - Generate a BusinessDecision manifest for
Drogon DG1 (Decision Gate 1 - Identify & Assess).

Reads:
  manifest_masterwp_drogon.json    - Reservoir ID
  manifest_wpcraw_drogon.json      - Raw REV WPC ID
  manifest_wpcstat_drogon.json     - Statistics REV WPC ID
  manifest_wpcparams_drogon.json   - ColumnBasedTable WPC ID (parameters)
  manifest_risk_drogon.json        - Risk IDs

Output:
  manifest_bd_drogon.json

Usage:
  py demo/drogon/gen_businessdecision_drogon.py
"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

SCRIPT_DIR = Path(__file__).resolve().parent

DEFAULT_ACL = {
    "owners":  ["data.default.owners@dev.dataservices.energy"],
    "viewers": ["data.office.global.viewers@dev.dataservices.energy"],
}
DEFAULT_LEGAL = {
    "legaltags": ["dev-equinor-private-default"],
    "otherRelevantDataCountries": ["NO"],
}


from _shared import load_json  # noqa: E402


def _find_id(manifest: Dict, kind_fragment: str) -> str:
    """Find the first record ID whose kind contains kind_fragment."""
    for md in manifest.get("MasterData", []):
        if kind_fragment in md.get("kind", ""):
            return md["id"]
    for wpc in manifest.get("Data", {}).get("WorkProductComponents", []):
        if kind_fragment in wpc.get("kind", ""):
            return wpc["id"]
    return ""


def _find_all_ids(manifest: Dict, kind_fragment: str) -> List[str]:
    ids = []
    for md in manifest.get("MasterData", []):
        if kind_fragment in md.get("kind", ""):
            ids.append(md["id"])
    return ids


def main():
    ap = argparse.ArgumentParser(description="Generate Drogon DG1 BusinessDecision manifest")
    ap.add_argument("--masterwp",  default=str(SCRIPT_DIR / "manifest_masterwp_drogon.json"))
    ap.add_argument("--rawvol",    default=str(SCRIPT_DIR / "manifest_wpcraw_drogon.json"))
    ap.add_argument("--statvol",   default=str(SCRIPT_DIR / "manifest_wpcstat_drogon.json"))
    ap.add_argument("--params",    default=str(SCRIPT_DIR / "manifest_wpcparams_drogon.json"))
    ap.add_argument("--activity",  default=str(SCRIPT_DIR / "manifest_activity_drogon.json"))
    ap.add_argument("--risks",     default=str(SCRIPT_DIR / "manifest_risk_drogon.json"))
    ap.add_argument("--devconcept", default=str(SCRIPT_DIR / "manifest_devconcept_drogon.json"))
    ap.add_argument("--geolabelset", default=str(
        SCRIPT_DIR / "records" /
        "019_dev_work-product-component--GeoLabelSet_f5c8b2d4-6a39-4eaf-9b72-8d4eaf1a3c96_1.json"
    ), help="GeoLabelSet record JSON (generated by gengeolabelset_drogon.py)")
    ap.add_argument("--manifest",  default=str(SCRIPT_DIR / "manifest_bd_drogon.json"))
    ap.add_argument("--id-prefix", default="dev")
    args = ap.parse_args()

    masterwp = load_json(args.masterwp)
    rawvol   = load_json(args.rawvol)
    statvol  = load_json(args.statvol)
    params   = load_json(args.params)
    risks    = load_json(args.risks)

    # Load activity manifest (generated by gen_activity_drogon.py).
    # Falls back to old WPC-based list when the manifest does not yet exist.
    activity_id = ""
    activity_manifest_path = Path(args.activity)
    if activity_manifest_path.exists():
        act_man = load_json(str(activity_manifest_path))
        activity_id = _find_id(act_man, "work-product-component--Activity:")

    keyuncert = {}

    reservoir_id = _find_id(masterwp, "master-data--Reservoir:")
    raw_wpc_id   = _find_id(rawvol, "ReservoirEstimatedVolumes")
    stat_wpc_id  = _find_id(statvol, "ReservoirEstimatedVolumes")
    params_wpc_id = _find_id(params, "ColumnBasedTable")
    risk_ids     = _find_all_ids(risks, "master-data--Risk:")

    # DevelopmentConcept WPC
    devconcept_wpc_id = ""
    if Path(args.devconcept).exists():
        devconcept_wpc_id = _find_id(load_json(args.devconcept), "DevelopmentConcept")

    # GeoLabelSet (written directly to records/ by gengeolabelset_drogon.py)
    geolabelset_id = ""
    gls_path = Path(args.geolabelset)
    if gls_path.exists():
        geolabelset_id = load_json(str(gls_path)).get("id", "")

    # PriorActivityIDs: use the merged Activity record when available;
    # fall back to the three WPC IDs for backward compatibility.
    prior_activity_ids = (
        [activity_id] if activity_id
        else [x for x in [raw_wpc_id, stat_wpc_id, params_wpc_id] if x]
    )

    # ETPDataspace: RDDMS dataspace holding the RESQML artefacts linked to this BD
    dataspace_id = f"{args.id_prefix}:dataset--ETPDataspace:maap-drogon_dg:1"

    bd_id = f"{args.id_prefix}:master-data--BusinessDecision:Drogon-DG1-Identify:1"

    bd_record = {
        "id":    bd_id,
        "kind":  "osdu:wks:master-data--BusinessDecision:1.0.0",
        "acl":   DEFAULT_ACL,
        "legal": DEFAULT_LEGAL,
        "data": {
            "Name": "Drogon DG1 - Identify & Assess",
            "Description": (
                "DG1 volume assessment of the Valysar formation, Drogon field. "
                "P10/P50/P90 oil & gas estimates across 7 segments."
            ),
            "ProjectName": "Drogon Field Development",
            "DecisionLevelID": f"{args.id_prefix}:reference-data--DecisionLevel:DG1:",
            "ApprovalStatusID": f"{args.id_prefix}:reference-data--DecisionApprovalStatus:Approved:",
            "DecisionDueDate": "2026-03-15",
            "DecisionDate": "2026-02-28",
            "DecisionSummary": "Assess Valysar in-place volumes and recommend proceed/no-go for DG2.",
            "RiskIDs": risk_ids,
            "PriorActivityIDs": prior_activity_ids,
            "Parameters": [
                {
                    "Title": "Raw volumes (per realisation)",
                    "Selection": "Per-realisation FMU output",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:Input:",
                    "DataObjectParameter": raw_wpc_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "REV-raw"},
                    ],
                },
                {
                    "Title": "Statistical volumes (P10/P50/P90)",
                    "Selection": "P10/P50/P90 aggregates",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:Input:",
                    "DataObjectParameter": stat_wpc_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "REV-stats"},
                    ],
                },
                {
                    "Title": "Valysar parameters (OWC, porosity)",
                    "Selection": "Per-segment/facies inputs",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:Input:",
                    "DataObjectParameter": params_wpc_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "ColumnBasedTable-params"},
                    ],
                },
                {
                    "Title": "Reservoir scope",
                    "Selection": "Valysar reservoir",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:InputReference:",
                    "DataObjectParameter": reservoir_id,
                },
                {
                    "Title": "GeoModelDataspace",
                    "Selection": "RDDMS geomodel EPC store",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:InputReference:",
                    "DataObjectParameter": dataspace_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "ETPDataspace"},
                    ],
                },
                *([{
                    "Title": "Development Concept",
                    "Selection": "DG1 concept definition",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:Input:",
                    "DataObjectParameter": devconcept_wpc_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "DevelopmentConcept"},
                    ],
                }] if devconcept_wpc_id else []),
                *([{
                    "Title": "GeoLabelSet (segment volumes + properties)",
                    "Selection": "Segment volume labels",
                    "ParameterKindID": f"{args.id_prefix}:reference-data--ParameterKind:DataObject:",
                    "ParameterRoleID": f"{args.id_prefix}:reference-data--ParameterRole:Input:",
                    "DataObjectParameter": geolabelset_id,
                    "Keys": [
                        {"ParameterKey": "artifact", "StringParameterKey": "GeoLabelSet"},
                    ],
                }] if geolabelset_id else []),
            ],
            # ── Canonical: Personnel[] ← Authors ──
            "Personnel": [
                {
                    "Name": "Inge Lehmann",
                    "ProjectRoleID": f"{args.id_prefix}:reference-data--ProjectRole:GeoscienceLead:",
                    "Organisation": "Drogon Subsurface",
                },
                {
                    "Name": "Vladimir Vernadsky",
                    "ProjectRoleID": f"{args.id_prefix}:reference-data--ProjectRole:ReservoirEngineer:",
                    "Organisation": "Drogon Reservoir Management",
                },
                {
                    "Name": "Friedrich Mohs",
                    "ProjectRoleID": f"{args.id_prefix}:reference-data--ProjectRole:Petrophysicist:",
                    "Organisation": "Drogon Petec",
                },
                {
                    "Name": "Abraham G. Werner",
                    "ProjectRoleID": f"{args.id_prefix}:reference-data--ProjectRole:FMULead:",
                    "Organisation": "Drogon Geomodelling",
                },
            ],
            # ── Canonical: DecisionOwners/Makers/Contributors[] ← ReviewTeam ──
            "DecisionOwners": [
                {"Name": "Inge Lehmann", "Organisation": "Drogon Subsurface Lead"},
            ],
            "DecisionMakers": [
                {"Name": "Pyotr Kropotkin", "Organisation": "Drogon Project Director"},
            ],
            "Contributors": [
                {"Name": "Abraham G. Werner", "Organisation": "Drogon Geomodelling"},
                {"Name": "Alexander von Humboldt", "Organisation": "ST MSU Subsurface QA"},
            ],
            # ── Canonical: Remarks[] ← Recommendations ──
            "Remarks": [
                {"Remark": r, "RemarkSource": "DG1 Recommendations"}
                for r in [
                    "Upgrade FMU to Level 3 with 50+ realisations for DG2",
                    "Acquire core data in NorthSea and EastLobe for porosity calibration",
                    "Evaluate seismic reprocessing for Valysar depth conversion",
                    "Cross-discipline OWC sensitivity review on recovery factors",
                    "Production testing across fault blocks for pressure connectivity (target DG2, 2027-Q2)",
                    "Plan up to 4 infill wells; include CAPEX 50-150 MUSD in DG2 sensitivity",
                ]
            ],
            # ── ProjectSpecifications[] ← KeyEconomics (DG1 preliminary) ──
            "ProjectSpecifications": [
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:NPV_10pct:",      "DataQuantityParameter": 280,  "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:MUSD:"},
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:IRR:",             "DataQuantityParameter": 12,   "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:%:"},
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:CAPEX:",           "DataQuantityParameter": 6500, "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:MNOK:"},
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:OPEX_pa:",         "DataQuantityParameter": 350,  "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:MNOK:"},
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:BreakevenOil:",    "DataQuantityParameter": 55,   "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:USD/bbl:"},
                {"ParameterTypeID": f"{args.id_prefix}:reference-data--ParameterType:Payback:",         "DataQuantityParameter": 9.0,  "UnitOfMeasureID": f"{args.id_prefix}:reference-data--UnitOfMeasure:a:"},
            ],
            # ── ActivityStates[] ← ScheduleMilestones ──
            "ActivityStates": [
                {"EffectiveDateTime": "2025-12-15", "ActivityStatusID": f"{args.id_prefix}:reference-data--ActivityStatus:Completed:", "Remark": "DG1 Identify & Assess"},
                {"EffectiveDateTime": "2026-03-01", "ActivityStatusID": f"{args.id_prefix}:reference-data--ActivityStatus:Planned:",   "Remark": "DG2 Concept Select"},
                {"EffectiveDateTime": "2027-01-01", "ActivityStatusID": f"{args.id_prefix}:reference-data--ActivityStatus:Planned:",   "Remark": "DG3 FEED"},
                {"EffectiveDateTime": "2027-07-01", "ActivityStatusID": f"{args.id_prefix}:reference-data--ActivityStatus:Planned:",   "Remark": "FID / DG4"},
            ],
            "ancestry": {
                "parents": [activity_id] if activity_id else [],
                "children": [],
            },
            "ext": {
                "equinor": {
                    "Alternatives": [
                        {
                            "Name": "Proceed to DG2 — full 7-segment development",
                            "Rank": 1,
                            "Rationale": "All 7 segments show commercial volumes; porosity risk manageable.",
                            "RecommendedAction": "Approve",
                        },
                        {
                            "Name": "Reduced scope — CentralHorst + CentralSouth only",
                            "Rank": 2,
                            "Rationale": "Best economics, lowest uncertainty; leaves ~40% upside for later.",
                            "RecommendedAction": "Consider",
                        },
                        {
                            "Name": "Defer — acquire more appraisal data",
                            "Rank": 3,
                            "Rationale": "Floodplain porosity poorly constrained; more core data recommended.",
                            "RecommendedAction": "Fallback",
                        },
                    ],
                    "UncertaintySummary": {
                        "Basis": "FMU static volumes, 3 realisations, 7 segments, 3 facies",
                        "Note": "See stat WPC for P10/P50/P90 per segment & facies (m³).",
                        "TotalRealisations": 3,
                        "MethodologyReference": "FMU Level 2 static uncertainty workflow (Valysar v1)",
                        "StaticInPlace_Oil_MSm3": {
                            "P90": 28.5,
                            "P50": 34.5,
                            "P10": 42.0,
                        },
                        "Recoverable_Oil_MSm3": {
                            "P90": 5.8,
                            "P50": 8.2,
                            "P10": 11.5,
                        },
                        "RecoveryFactor_pct": {
                            "P90": 22.0,
                            "P50": 27.5,
                            "P10": 32.0,
                        },
                    },
                },
            },
        },
    }

    manifest = {
        "kind": "osdu:wks:Manifest:1.0.0",
        "ReferenceData": [],
        "MasterData": [bd_record],
        "Data": {
            "Datasets": [],
            "WorkProductComponents": [],
            "WorkProducts": [],
        },
    }

    Path(args.manifest).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"BusinessDecision manifest written → {args.manifest}")
    print(f"  BD ID        : {bd_id}")
    print(f"  Reservoir ref: {reservoir_id}")
    print(f"  Raw REV ref  : {raw_wpc_id}")
    print(f"  Stat REV ref : {stat_wpc_id}")
    print(f"  Params ref   : {params_wpc_id}")
    print(f"  Stat WPC ref : {stat_wpc_id}")
    print(f"  Risk refs    : {risk_ids}")


if __name__ == "__main__":
    main()
